export const idData = {
  artwork1: 'Di era di mana konektivitas digital menjadi yang utama, "Kami Mendengar Anda di Sini dan di Sana" muncul sebagai eksplorasi tentang efek polarisasi internet terhadap masyarakat, terutama ditonjolkan dalam atmosfer panas pemilihan presiden Indonesia yang akan datang. Instalasi suara spasial ini menyelami kebisingan media sosial, mengubahnya menjadi pengalaman auditori yang mendalam yang mencakup kekacauan dan ketidaksepakatan dari percakapan online.',
  artwork2: 'Instalasi ini menggarisbawahi perpecahan sosial yang diperbesar oleh internet. Saat pengunjung masuk ke ruang tersebut, mereka dikelilingi oleh hiruk pikuk suara yang berasal dari berbagai arah, mencerminkan aliran pendapat, debat, dan bentrokan yang tak henti-hentinya yang ditandai oleh interaksi digital. Kekacauan auditori ini tidak hanya mencerminkan keragaman pandangan tetapi juga sifat yang mendominasi dari komunikasi digital di era yang dipenuhi politik. Ini menyajikan manifestasi sensori dari kesenjangan digital, di mana faksi-faksi ideologis terhubung dan terputus, terlibat dalam perselisihan virtual. Elemen interaktif mengundang peserta untuk berkontribusi pada lanskap suara yang berkembang, melambangkan sifat partisipatif namun seringkali memecah belah dari media sosial.',
  artist1: 'Tomy Herseta (lahir 1992) adalah seorang desainer, direktur kreatif, musisi elektronik, dan dosen. Metodenya dalam bekerja, mengajar, dan mengarahkan selalu berada dalam ranah interdisipliner dengan menggunakan pendekatan spasial sebagai fondasi intinya. Ia meraih gelar sarjana dalam Desain Interior dari Institut Teknologi Bandung dan gelar magister dalam Seni Seni Pertunjukan dari HKU University of the Arts Utrecht.\n\n',
  artist2: 'Karyanya biasanya mengangkat pertanyaan tentang hubungan antara manusia, media, dan masyarakat dalam informasi dan komunikasi yang dimediasi dan bagaimana lingkungan digital dan fisik saling terhubung. Sementara musiknya umumnya merupakan campuran antara lanskap suara ambient dan suasana sinematik yang membangkitkan emosi dan munculnya rasa dari ruang atau keadaan tertentu yang berusaha menghasilkan citra melalui persepsi auditori. Pertunjukannya sebagian besar memeluk intuisi dan kolaborasi melalui improvisasi langsung.',
  artist3: 'Ia telah berpartisipasi dalam beberapa pameran dan festival di seluruh Indonesia, Asia Tenggara, dan Eropa, seperti Bandung New Emergence, ARTJOG, London Design Biennale, CTM Festival, Prague Quadrennial, dan lain-lain. Saat ini ia sibuk antara mengarahkan kreatif di sebuah merek perusahaan berbasis di Jakarta dan mengajar di universitas di Bandung, sambil tetap mempertahankan praktik seninya dengan berkolaborasi dengan entitas terkemuka seperti Goethe Institut, Institut Pertunjukan Garasi, Indonesia Fashion Week, dan lain-lain.'
};

export const enData = {
  artwork1: 'In an age where digital connectivity reigns supreme, "We Hear You Here and There" emerges as an exploration of the internet\'s polarizing effects on society, particularly accentuated in the heated atmosphere of Indonesia\'s upcoming presidential elections. This spatial sound installation delves into the cacophony of social media, transforming it into an immersive auditory experience that encapsulates the chaos and discord of online discourse.',
  artwork2: 'The installation underscores the societal schisms amplified by the internet. As visitors step into the space, they are enveloped in a whirlwind of voices and sounds emanating from various directions, mirroring the relentless stream of opinions, debates, and clashes that characterize digital interactions. This auditory chaos not only reflects the diversity of views but also the overwhelming nature of digital communication in a politically charged era. It presents a sensory manifestation of the digital divide, where ideological factions are both connected and disconnected, engaged in virtual disputes. Interactive elements invite attendees to contribute to the evolving soundscape, symbolizing the participatory yet often divisive nature of social media.',
  artist1: 'Tomy Herseta (b. 1992) is a designer, creative director, electronic musician and lecturer. His method in working, teaching and directing is always in the realm of interdisciplinarity by using spatial approach as his core foundation. He earned his bachelor in Interior Design from Institut Teknologi Bandung and master in Scenography from HKU University of the Arts Utrecht.',
  artist2: 'His work usually raises questions of the relation between human, media and society within mediated information and communication and how digital and physical environments are interconnected. While his music is generally a mixture between ambient soundscape and cinematic atmosphere that evoke an emotion and emerge the sense of certain spaces or circumstances which attempts to generate imagery through auditory perception. His performances mostly embrace intuition and collaboration through live improvisation.',
  artist3: 'He has participated in several exhibitions and festivals across Indonesia, South East Asia and Europe, such as Bandung New Emergence, ARTJOG, London Design Biennale, CTM Festival, Prague Quadrennial, amongst others. He is currently juggling between creative directing at a Jakarta based corporate brand and teaching at the university in Bandung, while still maintaining his artistic practice by collaborating with notable entities such as Goethe Institut, Garasi Performance Institute, Indonesia Fashion Week, amongst others.'
};
